name: Docker Deploy

on:
  push:
    branches:
      - main  # The pipeline runs on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Environment for running jobs

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v2  # GitHub action to clone the repository

      # Step 2: Set up Docker Buildx for advanced Docker build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add Docker username as a GitHub secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add Docker password as a GitHub secret

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Context is set to the root of the repository
          push: true
          tags: barath0023/docimg:latest  # Replace 'docimg' with your Docker image name if needed

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'barath'  # Replace with your Azure Web App name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Add Azure publish profile as a GitHub secret
